package wildlife.view.renderer;

/**
 * Abstraction for an OpenGL texture.
 * External modules implement this interface and inject it into the SpriteBatch.
 * This keeps the renderer completely decoupled from asset-loading logic.
 */
public interface ITexture {

    /** @return the OpenGL texture ID (name) generated by glGenTextures. */
    int getTextureId();

    /** @return the width of the texture in pixels. */
    int getWidth();

    /** @return the height of the texture in pixels. */
    int getHeight();

    /** Bind this texture to GL_TEXTURE_2D. */
    void bind();

    /** Unbind any texture from GL_TEXTURE_2D. */
    void unbind();
}
